@startuml

title __DOMAIN's Class Diagram__\n

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicInfo {
          - songs : List<SongsBean>
          + getSongs()
          + setSongs()
          + toString()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicInfo.SongsBean {
          - alia : List<String>
          - ar : List<ArBean>
          - fee : int
          - id : int
          - mv : int
          - name : String
          + getAl()
          + getAlia()
          + getAr()
          + getFee()
          + getId()
          + getMv()
          + getName()
          + setAl()
          + setAlia()
          + setAr()
          + setFee()
          + setId()
          + setMv()
          + setName()
          + toString()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicInfo.SongsBean.AlBean {
          - id : int
          - name : String
          - picUrl : String
          + getId()
          + getName()
          + getPicUrl()
          + setId()
          + setName()
          + setPicUrl()
          + toString()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicInfo.SongsBean.ArBean {
          - id : int
          - name : String
          + getId()
          + getName()
          + setId()
          + setName()
          + toString()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicList {
          + getResult()
          + setResult()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicList.ResultBean {
          - songs : List<SongsBean>
          + getSongs()
          + setSongs()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicList.ResultBean.SongsBean {
          - id : String
          + getId()
          + setId()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicListInfo {
          - albumName : String
          - alia : String
          - artistsName : String
          - fee : int
          - id : String
          - mvid : int
          - name : String
          - picUrl : String
          - url : String
          + getAlbumName()
          + getAlia()
          + getArtistsName()
          + getFee()
          + getId()
          + getMvid()
          + getName()
          + getPicUrl()
          + getUrl()
          + setMusicInfo()
          + setUrl()
          + toString()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicUrl {
          - data : List<DataBean>
          + getData()
          + setData()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace domain {
      class com.shuai.musicplayer2.domain.MusicUrl.DataBean {
          - url : String
          + getUrl()
          + setUrl()
      }
    }
  }
  

  com.shuai.musicplayer2.domain.MusicInfo +-down- com.shuai.musicplayer2.domain.MusicInfo.SongsBean
  com.shuai.musicplayer2.domain.MusicInfo.SongsBean o-- com.shuai.musicplayer2.domain.MusicInfo.SongsBean.AlBean : al
  com.shuai.musicplayer2.domain.MusicInfo.SongsBean +-down- com.shuai.musicplayer2.domain.MusicInfo.SongsBean.AlBean
  com.shuai.musicplayer2.domain.MusicInfo.SongsBean +-down- com.shuai.musicplayer2.domain.MusicInfo.SongsBean.ArBean
  com.shuai.musicplayer2.domain.MusicList o-- com.shuai.musicplayer2.domain.MusicList.ResultBean : result
  com.shuai.musicplayer2.domain.MusicList +-down- com.shuai.musicplayer2.domain.MusicList.ResultBean
  com.shuai.musicplayer2.domain.MusicList.ResultBean +-down- com.shuai.musicplayer2.domain.MusicList.ResultBean.SongsBean
  com.shuai.musicplayer2.domain.MusicUrl +-down- com.shuai.musicplayer2.domain.MusicUrl.DataBean


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
