@startuml

title __UTILS's Class Diagram__\n

  namespace com.shuai.musicplayer2 {
    namespace utils {
      class com.shuai.musicplayer2.utils.DlCRUD {
          {static} + sDlList : List<String>
          {static} - TAG : String
          - mFile : File
          - mUrl : String
          + deleteMusic()
          + downLoadMusic()
          + getDL()
          - downLoad()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace utils {
      class com.shuai.musicplayer2.utils.FastBlur {
          {static} + doBlur()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace utils {
      class com.shuai.musicplayer2.utils.GetMenuList {
          {static} + sCount : int
          {static} - TAG : String
          - mMusicListTask : Call<MusicList>
          - mRetrofit : Retrofit
          - mSongsId : List<String>
          + GetMenuList()
          + getMusicList()
          - saveMusicListId()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace utils {
      class com.shuai.musicplayer2.utils.LikeCRUD {
          {static} - TAG : String
          + likeAdd()
          + likeDelete()
          + likeSelete()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace utils {
      class com.shuai.musicplayer2.utils.MenuList {
          {static} + sCount : int
          {static} + sMusicListInfo : List<MusicListInfo>
          {static} - TAG : String
          - mMusicInfoTask : Call<MusicInfo>
          - mMusicListTask : Call<MusicList>
          - mMusicUrlTask : Call<MusicUrl>
          - mNum : int
          - mRetrofit : Retrofit
          - mSongsId : List<String>
          + MenuList()
          - updateInfo()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace utils {
      class com.shuai.musicplayer2.utils.RetrofitManager {
          {static} - mRetrofit : Retrofit
          {static} + getRetrofit()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace utils {
      class com.shuai.musicplayer2.utils.SqlHelper {
          + SqlHelper()
          + onCreate()
          + onUpgrade()
      }
    }
  }
  

  com.shuai.musicplayer2.utils.GetMenuList o-- com.shuai.musicplayer2.api.Api : mApi
  com.shuai.musicplayer2.utils.MenuList o-- com.shuai.musicplayer2.api.Api : mApi
  com.shuai.musicplayer2.utils.SqlHelper -up-|> android.database.sqlite.SQLiteOpenHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
