@startuml

title __PRESENTER's Class Diagram__\n

  namespace com.shuai.musicplayer2 {
    namespace presenter {
      class com.shuai.musicplayer2.presenter.PlayerPresenter {
          {static} + sCurrentState : int
          {static} - TAG : String
          - mCurrentPosition : int
          - mPlayer : MediaPlayer
          - mTimer : Timer
          + pauseOrResume()
          + registerIPlayViewController()
          + seekTo()
          + start()
          + startTimeTask()
          + stop()
          + stopTimeTask()
          + unregisterIPlayViewController()
          - initMediaPlayer()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace presenter {
      class com.shuai.musicplayer2.presenter.PlayerPresenter.SeekTimeTask {
          + run()
      }
    }
  }
  

  com.shuai.musicplayer2.presenter.PlayerPresenter .up.|> com.shuai.musicplayer2.interfaces.IPlayerController
  com.shuai.musicplayer2.presenter.PlayerPresenter -up-|> android.os.Binder
  com.shuai.musicplayer2.presenter.PlayerPresenter o-- com.shuai.musicplayer2.presenter.PlayerPresenter.SeekTimeTask : mTimeTask
  com.shuai.musicplayer2.presenter.PlayerPresenter o-- com.shuai.musicplayer2.interfaces.IPlayerViewController : mViewController
  com.shuai.musicplayer2.presenter.PlayerPresenter +-down- com.shuai.musicplayer2.presenter.PlayerPresenter.SeekTimeTask
  com.shuai.musicplayer2.presenter.PlayerPresenter.SeekTimeTask -up-|> java.util.TimerTask


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
