@startuml

title __ADAPTER's Class Diagram__\n

  namespace com.shuai.musicplayer2 {
    namespace adapter {
      class com.shuai.musicplayer2.adapter.MusicListAdapter {
          ~ mMusicListInfo : List<MusicListInfo>
          - mContext : Context
          - mItemView : View
          + getItemCount()
          + getItemViewType()
          + onBindViewHolder()
          + onCreateViewHolder()
          + setData()
          + setOnLongClickListener()
          + setOnMusicClickListener()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace adapter {
      class com.shuai.musicplayer2.adapter.MusicListAdapter.InnerHolder {
          - mPosition : int
          + InnerHolder()
          + setPosition()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace adapter {
      interface com.shuai.musicplayer2.adapter.MusicListAdapter.OnLongClickListener {
          {abstract} + onLongClick()
      }
    }
  }
  

  namespace com.shuai.musicplayer2 {
    namespace adapter {
      interface com.shuai.musicplayer2.adapter.MusicListAdapter.OnMusicClickListener {
          {abstract} + onMusicClick()
      }
    }
  }
  

  com.shuai.musicplayer2.adapter.MusicListAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.shuai.musicplayer2.adapter.MusicListAdapter o-- com.shuai.musicplayer2.adapter.MusicListAdapter.OnLongClickListener : mLongClickListener
  com.shuai.musicplayer2.adapter.MusicListAdapter o-- com.shuai.musicplayer2.adapter.MusicListAdapter.OnMusicClickListener : mMusicClickListener
  com.shuai.musicplayer2.adapter.MusicListAdapter +-down- com.shuai.musicplayer2.adapter.MusicListAdapter.InnerHolder
  com.shuai.musicplayer2.adapter.MusicListAdapter +-down- com.shuai.musicplayer2.adapter.MusicListAdapter.OnLongClickListener
  com.shuai.musicplayer2.adapter.MusicListAdapter +-down- com.shuai.musicplayer2.adapter.MusicListAdapter.OnMusicClickListener
  com.shuai.musicplayer2.adapter.MusicListAdapter.InnerHolder -up-|> androidx.recyclerview.widget.RecyclerView.ViewHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
